### Get Users
GET http://localhost:3000/users HTTP/1.1

### Get User
GET http://localhost:3000/users/2bb65ab3-cc42-40a8-b693-451781532851 HTTP/1.1
### Create user
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "name": "Angel",
    "email": "angel@gmail.com"
}

### Update user
PATCH http://localhost:3000/users/2bb65ab3-cc42-40a8-b693-451781532851 HTTP/1.1
Content-Type: application/json

{
    "name": "Carlitos"
}

### Add Order to User
POST http://localhost:3000/users/12f370bc-0468-43ea-bd78-13407d614f15/orders HTTP/1.1
Content-Type: application/json

{
    "products": [
        {"name": "Fun Calculator", "price": 13800},
        {"name": "Car Wheels", "price": 24.99}
    ]
}